apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: helm-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: helm-service-account
    namespace: jenkins
roleRef:
  kind: ClusterRole
  name: helm-clusterrole
  apiGroup: rbac.authorization.k8s.io
