apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.goApp.labels.app | default "go-app" }}
  name: {{ .Values.goApp.name | default "go-app" }}
spec:
  ports:
    - port: {{ .Values.goApp.service.port | default 8080 }}
      protocol: TCP
      targetPort: {{ .Values.goApp.service.targetPort | default 8080 }}
  selector:
    app: {{ .Values.goApp.labels.app | default "go-app" }}
  type: {{ .Values.goApp.service.type | default "ClusterIP" }}
