apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.nodeApp.labels.app | default "node-app" }}
  name: {{ .Values.nodeApp.name | default "node-app" }}
spec:
  ports:
    - port: {{ .Values.nodeApp.service.port | default 3000 }}
      protocol: TCP
      targetPort: {{ .Values.nodeApp.service.targetPort | default 3000 }}
  selector:
    app: {{ .Values.nodeApp.labels.app | default "node-app" }}
  type: {{ .Values.nodeApp.service.type | default "ClusterIP" }}
